//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::bet::Entity as Bet;
pub use super::candidate::Entity as Candidate;
pub use super::r#match::Entity as Match;
pub use super::user::Entity as User;
